// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RaceDay.API.Data;

#nullable disable

namespace RaceDay.API.Migrations
{
    [DbContext(typeof(RaceDayDbContext))]
    [Migration("20260930052934_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RaceDay.API.Models.Category", b =>
                {
                    b.Property<int>("CategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryID"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6,2)");

                    b.HasKey("CategoryID");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.ToTable("CATEGORY", (string)null);
                });

            modelBuilder.Entity("RaceDay.API.Models.Enrolment", b =>
                {
                    b.Property<int>("EnrolmentID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EnrolmentID"));

                    b.Property<DateTime>("EnrolmentDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("EnrolmentStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EventCategoryID")
                        .HasColumnType("int");

                    b.Property<int>("ParticipantID")
                        .HasColumnType("int");

                    b.Property<int>("RaceNumber")
                        .HasColumnType("int");

                    b.HasKey("EnrolmentID");

                    b.HasIndex("ParticipantID");

                    b.HasIndex("EventCategoryID", "RaceNumber")
                        .IsUnique();

                    b.ToTable("ENROLMENT", null, t =>
                        {
                            t.HasCheckConstraint("CK_ENROLMENT_Status", "[EnrolmentStatus] IN ('Pending', 'Confirmed', 'Cancelled', 'Completed')");
                        });
                });

            modelBuilder.Entity("RaceDay.API.Models.Event", b =>
                {
                    b.Property<int>("EventID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventID"));

                    b.Property<DateTime>("CreatedDate")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DistanceKm")
                        .HasColumnType("decimal(6,2)");

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int>("OrganiserID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("EventID");

                    b.HasIndex("OrganiserID");

                    b.ToTable("EVENT", null, t =>
                        {
                            t.HasCheckConstraint("CK_EVENT_Status", "[Status] IN ('Upcoming', 'Open', 'Closed', 'Completed', 'Cancelled')");

                            t.HasCheckConstraint("CK_EVENT_Type", "[EventType] IN ('Run', 'Walk', 'Cycle')");
                        });
                });

            modelBuilder.Entity("RaceDay.API.Models.EventCategory", b =>
                {
                    b.Property<int>("EventCategoryID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EventCategoryID"));

                    b.Property<int>("AvailableSlots")
                        .HasColumnType("int");

                    b.Property<int>("CategoryID")
                        .HasColumnType("int");

                    b.Property<decimal>("EntryFee")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("EventID")
                        .HasColumnType("int");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.HasKey("EventCategoryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("EventID");

                    b.ToTable("EVENT_CATEGORY", null, t =>
                        {
                            t.HasCheckConstraint("CK_EVENT_CATEGORY_AvailableSlots", "[AvailableSlots] >= 0 AND [AvailableSlots] <= [MaxParticipants]");

                            t.HasCheckConstraint("CK_EVENT_CATEGORY_EntryFee", "[EntryFee] >= 0");

                            t.HasCheckConstraint("CK_EVENT_CATEGORY_MaxParticipants", "[MaxParticipants] > 0");
                        });
                });

            modelBuilder.Entity("RaceDay.API.Models.Result", b =>
                {
                    b.Property<int>("ResultID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ResultID"));

                    b.Property<int>("EnrolmentID")
                        .HasColumnType("int");

                    b.Property<TimeSpan?>("FinishTime")
                        .HasColumnType("time");

                    b.Property<int?>("Position")
                        .HasColumnType("int");

                    b.Property<string>("ResultStatus")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ResultID");

                    b.HasIndex("EnrolmentID")
                        .IsUnique();

                    b.ToTable("RESULT", null, t =>
                        {
                            t.HasCheckConstraint("CK_RESULT_Position", "[Position] IS NULL OR [Position] > 0");

                            t.HasCheckConstraint("CK_RESULT_Status", "[ResultStatus] IN ('Pending', 'Finished', 'DNS', 'DNF')");
                        });
                });

            modelBuilder.Entity("RaceDay.API.Models.User", b =>
                {
                    b.Property<int>("UserID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserID"));

                    b.Property<DateTime>("DateCreated")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("UserID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("USER", null, t =>
                        {
                            t.HasCheckConstraint("CK_USER_Role", "[Role] IN ('Organiser', 'Participant')");
                        });
                });

            modelBuilder.Entity("RaceDay.API.Models.Enrolment", b =>
                {
                    b.HasOne("RaceDay.API.Models.EventCategory", "EventCategory")
                        .WithMany()
                        .HasForeignKey("EventCategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay.API.Models.User", "Participant")
                        .WithMany()
                        .HasForeignKey("ParticipantID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("EventCategory");

                    b.Navigation("Participant");
                });

            modelBuilder.Entity("RaceDay.API.Models.Event", b =>
                {
                    b.HasOne("RaceDay.API.Models.User", "Organiser")
                        .WithMany()
                        .HasForeignKey("OrganiserID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Organiser");
                });

            modelBuilder.Entity("RaceDay.API.Models.EventCategory", b =>
                {
                    b.HasOne("RaceDay.API.Models.Category", "Category")
                        .WithMany("EventCategories")
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("RaceDay.API.Models.Event", "Event")
                        .WithMany("EventCategories")
                        .HasForeignKey("EventID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Event");
                });

            modelBuilder.Entity("RaceDay.API.Models.Result", b =>
                {
                    b.HasOne("RaceDay.API.Models.Enrolment", "Enrolment")
                        .WithOne("Result")
                        .HasForeignKey("RaceDay.API.Models.Result", "EnrolmentID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Enrolment");
                });

            modelBuilder.Entity("RaceDay.API.Models.Category", b =>
                {
                    b.Navigation("EventCategories");
                });

            modelBuilder.Entity("RaceDay.API.Models.Enrolment", b =>
                {
                    b.Navigation("Result");
                });

            modelBuilder.Entity("RaceDay.API.Models.Event", b =>
                {
                    b.Navigation("EventCategories");
                });
#pragma warning restore 612, 618
        }
    }
}
